# Generated by Django 5.1.2 on 2024-10-20 16:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100, verbose_name='Nome do Candidato')),
                ('Data de Nascimento', models.DateField(verbose_name='Data de Nascimento do Candidato')),
                ('Sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('I', 'Indefinido')], max_length=1, verbose_name='Sexo do Candidato')),
                ('Raça', models.CharField(choices=[('Negro', 'Negro'), ('Pardo', 'Pardo'), ('Amarelo', 'Amarelo'), ('Branco', 'Branco')], max_length=7, verbose_name='Raça do Candidato')),
                ('Telefone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='O telefone deve estar no formato: (99) 99999-9999', regex='(\\d{2}) \\d{5}-\\d{4}')], verbose_name='Numero de Telefone do Candidato')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email do Candidato')),
                ('Linkedin', models.URLField(verbose_name='Url do Linkedin do Candidato')),
            ],
            options={
                'verbose_name': 'Candidato',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instuição', models.CharField(max_length=200, verbose_name='Nome da Instituição de Formaçâo')),
                ('Escolaridade', models.CharField(choices=[('MI', 'Médio Incompleto'), ('MC', 'Médio Completo'), ('SI', 'Superior Incompleto'), ('SC', 'Superior Completo')], max_length=2, verbose_name='Nível de Escolaridade')),
                ('Curso', models.CharField(max_length=100, verbose_name='Nome do Curso')),
                ('Data Início', models.DateField(verbose_name='Data Inicio do Curso')),
                ('Data Fim', models.DateField(null=True, verbose_name='Data Fim do Curso')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.candidate')),
            ],
            options={
                'verbose_name': 'Escolaridade',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cargo', models.CharField(max_length=100, verbose_name='Cargo da Experiência')),
                ('Empresa', models.CharField(max_length=100, verbose_name='Nome da Empresa da Experiência')),
                ('Data Inicío', models.DateField(verbose_name='Data de inicío da Experiência')),
                ('Data Fim', models.DateField(null=True, verbose_name='Data de Fim da Experiência')),
                ('Descrição', models.TextField(verbose_name='Descrição da Experiência')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.candidate')),
            ],
            options={
                'verbose_name': 'Experiência Profissional',
            },
        ),
    ]
